### ISSUE TITLE
xp 

### ISSUE THREAD

**Issue by thisisgoodhash** [ioncodes/ESP-It#14]
Is it possible to make a cheat that can increase the amount of experience per game? Or so that you can simply set yourself the level you want, it’s very necessary

**Comment by ioncodes** [comment]
idk, feel free to figure it out

**Comment by thisisgoodhash** [comment]
If you are free, can you do this?

**Comment by ioncodes** [comment]
i dont take requests unless it's through the sponsorship or donation program

**Comment by thisisgoodhash** [comment]
What is the price for this work?

**Comment by ioncodes** [comment]
I don't take money directly for things related to public projects (read: only for private projects). The only "direct" form would be a GitHub sponsors subscription starting at 10$/month IIRC. I do accept other forms of material donations, I usually get either Steam keys or hardware components as donations. Of course, the higher the donation the higher the priority will be - I am currently already busy with a large backlog. Feel free to contact me on Discord.
