### ISSUE TITLE
 Stopped working

### ISSUE THREAD

**Issue by YuStep** [ioncodes/ESP-It#2]
Today I played for 3 hours with a working dll enabled via cheat engine and everything was fine. Then I closed the game, did my business and returned. And when I tried to connect the dll through the cheat engine, I started getting the error the game is crashing, and in the crash report from UE the following text

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000000000b0

GooGooGaaGaa!SDK::UKismetStringLibrary::Conv_StringToName() [C:\Users\User\Desktop\ESP-It-master\GooGooGaaGaa\Epic\SDK\Engine_functions.cpp:61589]
GooGooGaaGaa!MainThread() [C:\Users\User\Desktop\ESP-It-master\GooGooGaaGaa\main.cpp:118]
kernel32
ntdll

I tried to dig around and solve the problem myself, but unfortunately I do not have the same knowledge as the author. Therefore, I could not solve the problem on my own. But I found out that the problem is in this place UEngine* Engine = UEngine::GetEngine();

This is my code for debugging
UEngine* Engine = UEngine::GetEngine();
if (!Engine)
{
    printf("Engine is nullptr\n");
    return 1;
}
if (!Engine->GameViewport)
{
    printf("GameViewport is nullptr\n");
    return 1;
}
if (!Engine->ConsoleClass)
{
    printf("ConsoleClass is nullptr\n");
    return 1;
}

Output Engine is nullptr

It seems to me that the problem may be that the offset in this place has changed uintptr_t PostRender = VTable + 0x380;

But I'm not sure

I hope the author will quickly solve this problem.

**Comment by neol1no** [comment]
game updated to build 23234

**Comment by ioncodes** [comment]
fixed it
