### ISSUE TITLE
crush when inject

### ISSUE THREAD

**Issue by CR4SHgg** [ioncodes/ESP-It#4]
An Unreal process has crashed: UE-WitchIt

LoginId:27c633774061eb0cdcaa25900cc8077b
EpicAccountId:db45ccc687de489fb84dffa85a6e5b95

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION writing address 0x0000000180004da0

PropWitchHuntModule_Win64_Shipping
PropWitchHuntModule_Win64_Shipping
PropWitchHuntModule_Win64_Shipping
PropWitchHuntModule_Win64_Shipping
PropWitchHuntModule_Win64_Shipping
PropWitchHuntModule_Win64_Shipping
PropWitchHuntModule_Win64_Shipping
PropWitchHuntModule_Win64_Shipping
PropWitchHuntModule_Win64_Shipping
PropWitchHuntModule_Win64_Shipping
PropWitchHuntModule_Win64_Shipping
PropWitchHuntModule_Win64_Shipping
kernel32
ntdll

**Comment by ioncodes** [comment]
did they update it again?

**Comment by ioncodes** [comment]
fixed as per latest release
