### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by mornoseu** [ioncodes/ESP-It#9]
Hey, could u please tell me how to inject it. Cause i don´t think I know how it works. Thanks

**Comment by mornoseu** [comment]
![image](https://github.com/user-attachments/assets/58e6861e-4323-4eb1-84ad-0a13d7d67e3c)

**Comment by ioncodes** [comment]
not sure what the context of that screenshot is. you can use any dll injector, at least all the ones ive tried worked with all the common techniques
